<a href="https://colab.research.google.com/github/DilyorSodikov/NumPy/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [4]:
import numpy as np
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
numb = list(range(10))
arr = np.array(numb)

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [7]:
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [11]:
arr = np.arange(10)
val = arr.itemsize
print(val)

8


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [13]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [14]:
arr = np.zeros(12)
arr[6] = 1
print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [15]:
arr = np.arange(20,60)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [17]:
arr = np.arange(9)
arr1 = arr[::-1]
print(arr1)


[8 7 6 5 4 3 2 1 0]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [19]:
arr = np.arange(12,21).reshape(3,3)
print(arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [22]:
arr = np.array([3, 7, 0, 0, 9, 0])
arr1 = np.nonzero(arr)
print(arr1)

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [27]:
arr = np.random.randn(2,2,2)
print(arr)

[[[ 1.47683514  2.14477268]
  [-0.01488195  0.36839111]]

 [[-1.42206193  0.62550555]
  [ 0.48401473  0.97011107]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [31]:
arr = np.random.randn(9,9)
arr1 = np.min(arr)
arr2 = np.max(arr)
print(arr1,arr2)

-2.237662539700535 2.114100471581644


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [32]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [34]:
arr1 = np.random.randn(6,3)
arr2 = np.random.randn(3,4)
arr3 = np.dot(arr1, arr2)
print(arr3)

[[-0.76388925  2.3626517   0.21871207 -0.39637555]
 [ 0.7949576  -1.59302034  0.86083116  0.44927853]
 [-1.17919433  2.22041457 -1.23340277 -0.60750789]
 [-0.42403946  2.37758495 -1.27450967 -0.97293754]
 [-0.6022698  -1.16892769 -0.86482083  0.36800694]
 [ 0.09137443  3.04571467  0.6914247  -0.8225477 ]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [50]:
arr1 = np.array([1,2])
arr2 = np.array([4,5])
arr1>arr2
arr1<arr2
arr1>=arr2
arr1<=arr2

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [53]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-53-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-53-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-53-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [54]:
arr1 = np.arange(1,7)
arr2 = np.arange(4,10)
arr3 = np.intersect1d(arr1,arr2)
print(arr3)

[4 5 6]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [66]:
arr = np.random.randn(10)
arr1 = arr[arr>0]
foiz = arr1 - arr1 % 1
flor = np.floor(arr1)
typ = arr1.astype(int)
trun = np.trunc(arr1)
print(foiz)
print(flor)
print(typ)
print(trun)

[0. 1. 1. 0. 0.]
[0. 1. 1. 0. 0.]
[0 1 1 0 0]
[0. 1. 1. 0. 0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [68]:
arr = np.random.randn(3,3)
arr[0:] = np.arange(0,3)
print(arr)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [69]:
arr = np.random.randn(10)
arr1 = np.sort(arr)
print(arr1)

[-2.03022547 -1.38056797 -1.12463165 -0.78018926 -0.42115473 -0.28559947
  0.18064603  1.00723083  1.05771386  1.63081386]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [71]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
arr3 = np.array_equal(arr1,arr2)
print(arr3)

False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [72]:
arr1 = np.random.randn(6,3)
arr2 = np.random.randn(3,4)
arr3 = np.dot(arr1, arr2)
print(arr3)

[[-0.52678188 -1.21812303 -3.44052261 -4.07393625]
 [-3.26157995 -0.31863195 -2.47912284 -2.07682404]
 [ 4.58405439  0.72281158  2.19980615  1.30883105]
 [-3.22366916  0.17647723 -0.30368023  0.60026265]
 [-0.79137766 -1.39735931 -1.70004664 -1.81914334]
 [-0.2756785  -0.58407551 -1.38308622 -1.61443742]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [78]:
arr = np.random.randn(10)
arr1 = np.argmax(arr)
arr[arr1] = 0
print(arr)

[ 0.32780075 -1.35308987  0.31437437 -0.52651966  0.         -2.00461936
 -0.03619037 -0.64347795 -0.20548796  1.56288165]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [83]:
today = np.datetime64('today')
tomorrow = today + np.timedelta64(1,"D")
yesterday = today - np.timedelta64(1, "D")
print(today)
print(tomorrow)
print(yesterday)

2024-12-14
2024-12-15
2024-12-13


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [86]:
start = np.datetime64('2016-01-01')
end = np.datetime64('2016-02-01')
arr = np.arange(start, end, dtype='datetime64[D]')
print(arr)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [79]:
arr = np.random.randn(10)
arr1 = arr[arr>0]
foiz = arr1 - arr1 % 1
flor = np.floor(arr1)
typ = arr1.astype(int)
trun = np.trunc(arr1)
print(foiz)
print(flor)
print(typ)
print(trun)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [88]:
arr1 = np.arange(10)
arr3 = np.add.reduce(arr1)
print(arr3)

45


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [90]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros(17)
arr2[::4] = arr1
print(arr2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [98]:
from numpy.lib.stride_tricks import as_strided
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
w_size = 4
shape = (len(a) - w_size + 1, w_size)
strides = (a.strides[0], a.strides[0])
b = as_strided(a, shape=shape, strides=strides)
print(b)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [104]:
arr1 = np.array([1,2,4,4,5,5,5,6,1,1,2])
arr2 = np.bincount(arr1)
duplicates = np.where(arr2 > 1)[0]
for val in duplicates:
    print(f"Value: {val}, Count: {arr2[val]}")

Value: 1, Count: 3
Value: 2, Count: 2
Value: 4, Count: 2
Value: 5, Count: 3


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`